language: node_js
dist: trusty
node_js:
  - "10"
  - "11"

addons:
  sonarcloud:
    organization: "reacli"
    token:
      secure: ${SONAR_TOKEN}
install:
    - npm install
script:
  - npm test
  - sonar-scanner -X -Dsonar.projectVersion=${SONAR_VERSION}
