language: node_js
dist: trusty
node_js:
  - "9"
  - "10"
cache: npm
addons:
  sonarcloud:
    organization: "reacli"
    token:
      secure: ${SONAR_TOKEN}
install:
    - npm install
script:
  - npm run build
  - npm test
  - sonar-scanner -X -Dsonar.projectVersion=${SONAR_VERSION}
